# Python basics
In this lab we will be covering up following things
- list
- dictionary
- function
- numpy
- pandas



# Question 1

## List
Sequences in python are data structures that hold objects in an ordered array. Now, we will work on list, the most common sequence data type in python.

This is how you define a list in Python
- Here we are defining a list named "list_1" using square braces "[ ]"

In [99]:
list_1 = ['learning', 'python', 'is fun!']

There is another way to define a list in Python
- Here we are defining a list named "list_2" using list() method

In [102]:
list_2 = list(('learning', 'for', 'life'))
list_2

['learning', 'for', 'life']

### Append an element in a list
- Append number 10 to "list_1" given above
- Use append() method

In [100]:
list_1


['learning', 'python', 'is fun!']

In [107]:
list_1.append(10)
print(list_1)

['learning', 'python', 'is fun!', 10]


### Remove an element from a list
- Do this after completing the previous step
- Remove number 10 from "list_1"
- Use remove() method

In [108]:
print(list_1)

['learning', 'python', 'is fun!', 10]


In [109]:
list_1.remove(10)
print(list_1)

['learning', 'python', 'is fun!']


### Join two lists
- Join list_1 and list_2
- Extend list_1 using list_2
- Use extend() method
- you can also use "+" operator to add two lists

In [110]:
print(list_1)
print(list_2)

['learning', 'python', 'is fun!']
['learning', 'for', 'life']


In [111]:
list_1.extend(list_2)
print(list_1)

['learning', 'python', 'is fun!', 'learning', 'for', 'life']


### Question 4
Number List

Find Range and Mean of l3.

`l3 = [2,4,6,8]`

Hint: use **`len()`, `sum()`, `min()`, `max()`** functions
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [41]:
import numpy as np
l3 = [2,4,6,8]
print (l3)

[2, 4, 6, 8]


In [28]:
len(l3)

4

In [33]:
x = np.arange(2,10,2)
print (x)

meantest = np.mean(x)
print(meantest)

[2 4 6 8]
5.0


### Sum up all the elements in a list
- Sum all the elements in "list_3"
- Use sum() method

In [35]:
list_3 = np.arange(1,50,5)
print(list_3)

[ 1  6 11 16 21 26 31 36 41 46]


In [37]:
sum_list3 = sum(list_3)
print(sum_list3)

235


# Question 3

### Calculate mean of values in a list
- Calculate mean of "list_3"
- Mean = sum of all elements in the list / number of elements in the list

In [39]:
print(list_3)
print(np.mean(list_3))

[ 1  6 11 16 21 26 31 36 41 46]
23.5


### Count the occurence of an element in a given list
- There is list given below named "list_4"
- Count the occurence of number 5 in "list_4"
- Use count() method

In [40]:
list_4 = [1, 2, 3, 5, 7, 5, 8, 9, 5, 3, 0, 7, 5]

In [45]:
list_4.count(5)

4

# Question 4

## Function
- Below is a simple code to define function in python
- Below function named "sample_function" takes two arguments "a" and "b" and returns their product

In [0]:
def sample_function(a, b):
  product = a * b
  return product

- This is how you call a function in python

In [0]:
sample_function(2, 3)

6

### Define and call a function
- Define a function named "sum_three"
- It should take 3 numbers as arguments
- It should return the sum of 3 numbers
- Call the defined function giving required parameters

In [46]:
def sum_three(int1,int2,int3):
    sum = int1+int2+int3
    return sum


In [47]:
x = sum_three(20,30,50)
print(x)

100


## Lambda function
Anonymous function or no name function, which can be considered when you use a function only once


Below is an example of how you can define a lambda function

In [0]:
f = lambda x, y: x + y

Here's how you can call a lambda function using required parameters

### Define a lambda function
- Define a lambda function named "lambda_sum_three" which takes 3 arguments and sums them up
- Call the created function with required parameters

In [49]:
lambda_sum = lambda x, y, z: x + y + z
print(lambda_sum(20,30,50))

100


# Question 5

## Numpy

Numpy adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.



Let's import numpy

In [0]:
import numpy as np

Here's how you can create an array using numpy

In [0]:
np.array([1, 2, 3])

array([1, 2, 3])

### Create an identity array
- Create an identity 2d-array of order 3x3
- The identity array is a square array with ones on the main diagonal
- Use identity() method

In [56]:
identity_2d_array = np.ones([2, 2], dtype = int) 
output = identity_2d_array * 3
print(output)

[[3 3]
 [3 3]]


### Create a 2d array
- Create a 2d-array of order 3x3 named "sample_array"
- First row: 1, 2, 3
- Second row: 4, 5, 6
- Third row: 7, 8, 9
- Arranged in the same order as above
- Use array() method



In [58]:
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Question 6

### Add a number in all the elements of an array
- Add 1 to all the elements in the array "sample_array"
- "+" operator can be used to add a number to all elements in an array
- Similarly, you can do operations like scalar substraction, division, multiplication (operating on each element in the array)

In [59]:
print(sample_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
    sample_array_plus_1 = sample_array + 1
    print(sample_array_plus_1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Find mean of all elements in an array
- Find mean of all elements in the array "sample_array"
- Use mean() method


In [62]:
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
print(np.mean(sample_array))

5.0


### Calculate dot product of two arrays
- We are giving you two arrays "a" and "b"
- Find the dot product of a and b
- Use dot() method

In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [66]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

# Question 7

## Pandas

We have seen Numpy in the previous section. It is good at performing math operations on arrays. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

Here's how you can import pandas

In [67]:
import pandas as pd

## Series
Pandas series are almost same as arrays in numpy with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

Here's how you can create a series

In [0]:
pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])

key1    1
key2    2
key3    3
dtype: int64

## Dataframes

Dataframes are the primary data structure for pandas. Two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). Arithmetic operations align on both row and column labels. Can be thought of as a dict-like container for Series objects.

You can construct DataFrame from a dictionary

In [0]:
d = {'col1': [1, 2], 'col2': [3, 4]}
pd.DataFrame(data=d)

col1  col2
0     1     3
1     2     4

You can construct DataFrame from a numpy array

In [0]:
pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

### Select specific row in given dataframe
- There is a dataframe named "df" is given below
- You have to select second row in this dataframe
- You can use "loc"
- There are multiple ways of doing it


In [77]:
df = pd.DataFrame(np.array([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]), columns=['col1', 'col2', 'col3'])
print(df)
print(df.loc[1])


  col1 col2 col3
0    a    b    c
1    d    e    f
2    g    h    i
col1    d
col2    e
col3    f
Name: 1, dtype: object


### Select specific row and column value in given dataframe
- There is a dataframe named "df" is given above
- You have to select the value on first row and second column
- You have to do it using "loc" and "iloc" methods
- "loc" accepts labels for column name
- "iloc" accepts indexes


In [78]:
print(df)

  col1 col2 col3
0    a    b    c
1    d    e    f
2    g    h    i


In [87]:
print(df.loc[0,'col2'])
print(df.iloc[0,1])

b
b


# Question 8

## Working on dataset using dataframe

### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

1. mpg 	Miles/(US) gallon
2. cyl 	Number of cylinders
3. disp 	Displacement (cu.in.)
4. hp 	Gross horsepower
5. drat 	Rear axle ratio
6. wt 	Weight (1000 lbs)
7. qsec 	1/4 mile time
8. vs 	Engine (0 = V-shaped, 1 = straight)
9. am 	Transmission (0 = automatic, 1 = manual)
10. gear 	Number of forward gears
11. carb 	Number of carburetors 


Here's how you read a csv file in pandas
- Here we are loading mtcars dataset in a dataframe named "mtcars"

In [88]:
mtcars = pd.read_csv('mtcars.csv')

### Print first five rows of the dataframe
- Print first five rows of "mtcars" dataframe
- Use head() method

In [93]:
print(mtcars.head())
print(mtcars.loc[0:5])

                name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
                name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.1

### Print last five rows of the dataframe
- Print last five rows of "mtcars" dataframe
- Use tail() method

In [92]:
mtcars.tail()

name   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

### Display all the columns in a given dataframe
- Display all the column names of "mtcars" dataframe
- Use columns method

In [96]:
list(mtcars.columns)

['name',
 'mpg',
 'cyl',
 'disp',
 'hp',
 'drat',
 'wt',
 'qsec',
 'vs',
 'am',
 'gear',
 'carb']